### Register

POST http://localhost:8080/api/users
Accept: application/json
Content-Type: application/json

{
  "username": "reza123",
  "Password": "password",
  "name": "reza"
}

### Login

POST http://localhost:8080/api/auth/login
Accept: application/json
Content-Type: application/json

{
  "username": "reza123",
  "password": "password"
}

### Get Users
GET http://localhost:8080/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e


### Update users
PATCH http://localhost:8080/api/users/current
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

{
  "name" : "bambang"
}

### Create Contact
POST http://localhost:8080/api/contacts
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

{
  "firstName" : "",
  "lastName" : "Bambang",
  "email" : "yaml@example.com",
  "phone" : "080808080"
}

### Get Contact
GET http://localhost:8080/api/contacts/3f3b416f-e300-4353-a5b0-54cc5af5fa02
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

### Update Contact
PUT http://localhost:8080/api/contacts/3f3b416f-e300-4353-a5b0-54cc5af5fa02
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

{
  "firstName" : "XiFuTang"
}

### Delete Contact
DELETE http://localhost:8080/api/contacts/8d921acd-dc54-4d53-a0e8-72dbe1c93b29
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e







### Create Address
POST http://localhost:8080/api/contacts/8d921acd-dc54-4d53-a0e8-72dbe1c93b29/addresses
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

{
  "street" : "Jalan apa 2",
  "city" : "Kota",
  "province" : "Provincsei",
  "country" : "negara",
  "postalCode" : "1234"
}


### Update Address
PUT http://localhost:8080/api/contacts/8d921acd-dc54-4d53-a0e8-72dbe1c93b29/addresses/56bfc9f4-fab1-46bb-9ec5-006b337ce566
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

{
  "street" : "mau makan"
}


### Remove Address
DELETE http://localhost:8080/api/contacts/8d921acd-dc54-4d53-a0e8-72dbe1c93b29/addresses/0cae8fe6-9cdd-4f61-b201-a5d9b760cccb
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

### List Address
GET http://localhost:8080/api/contacts/8d921acd-dc54-4d53-a0e8-72dbe1c93b29/addresses
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e

### Get Address by Id
GET http://localhost:8080/api/contacts/8d921acd-dc54-4d53-a0e8-72dbe1c93b29/addresses/f801b871-668b-4e8b-8b31-ef814661c833
Accept: application/json
Content-Type: application/json
X-API-TOKEN: 9cd55b8d-aae9-44e2-a1d4-a3194076fe4e


